# Generated by Django 5.1.5 on 2025-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
