# Generated by Django 5.1.5 on 2025-02-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_etudiant_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse',
        ),
    ]
