# Generated by Django 4.2.11 on 2025-01-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_competence_etudiant_alter_cv_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='etudiant',
        ),
    ]
