# Generated by Django 5.1.5 on 2025-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_competence_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='design',
            field=models.CharField(choices=[('design1', 'Modèle Classique'), ('design2', 'Modèle Moderne'), ('design3', 'Modèle Créatif')], default='design1', max_length=20),
        ),
    ]
